// SPDX-FileCopyrightText: 2026 Nick Wolff <nick@wolff.tech>
// SPDX-License-Identifier: GPL-3.0-only

import Foundation
import GhosttyKit
import os

/// Owns a `ghostty_config_t` built from a `TerminalAppearance`.
///
/// libghostty only loads configuration from files, so the rendered text is
/// written to a temporary file, loaded, and deleted.
@MainActor
final class GhosttyConfig {
    nonisolated(unsafe) let handle: ghostty_config_t
    let diagnostics: [String]

    init(appearance: TerminalAppearance) throws {
        guard let handle = ghostty_config_new() else {
            throw TerminalError.configurationFailed(["ghostty_config_new returned null"])
        }
        self.handle = handle

        let text = GhosttyConfigText.render(appearance)
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("constellation-ghostty-\(UUID().uuidString).conf")
        do {
            try text.write(to: url, atomically: true, encoding: .utf8)
        } catch {
            ghostty_config_free(handle)
            throw TerminalError.configurationFailed(["could not write config: \(error)"])
        }
        defer { try? FileManager.default.removeItem(at: url) }

        ghostty_config_load_file(handle, url.path)
        ghostty_config_finalize(handle)

        var diagnostics: [String] = []
        for index in 0..<ghostty_config_diagnostics_count(handle) {
            let diagnostic = ghostty_config_get_diagnostic(handle, index)
            diagnostics.append(String(cString: diagnostic.message))
        }
        self.diagnostics = diagnostics
        for message in diagnostics {
            Log.terminal.warning("ghostty config diagnostic: \(message, privacy: .public)")
        }
    }

    deinit {
        ghostty_config_free(handle)
    }
}

/// Renders Ghostty configuration text. Kept separate from the C handle so the
/// output can be asserted in tests.
enum GhosttyConfigText {
    static func render(_ appearance: TerminalAppearance) -> String {
        var lines: [String] = [
            "# Generated by Constellation. Change settings in the app, not here.",
            // Start from no Ghostty.app bindings; Constellation owns shortcuts.
            "keybind = clear",
            "keybind = super+c=copy_to_clipboard",
            "keybind = super+v=paste_from_clipboard",
            "keybind = super+a=select_all",
            "keybind = super+equal=increase_font_size:1",
            "keybind = super+minus=decrease_font_size:1",
            "keybind = super+zero=reset_font_size",
            "keybind = shift+page_up=scroll_page_up",
            "keybind = shift+page_down=scroll_page_down",
            "font-size = \(formatNumber(appearance.fontSize))",
            "scrollback-limit = \(appearance.scrollbackLimitBytes)",
            "macos-option-as-alt = \(appearance.optionAsAlt)",
            // Remote hosts rarely have xterm-ghostty terminfo.
            "term = xterm-256color",
            // Constellation confirms closes and handles exits itself.
            "confirm-close-surface = false",
            "clipboard-read = ask",
            "clipboard-write = ask",
            "clipboard-paste-protection = true",
            "shell-integration = none",
            "window-padding-x = 4",
            "window-padding-y = 4",
            "auto-update = off",
            "window-save-state = never",
            "quit-after-last-window-closed = false",
        ]
        if let family = appearance.fontFamily, !family.isEmpty {
            lines.append("font-family = \(family)")
        }
        if let theme = appearance.theme, !theme.isEmpty {
            lines.append("theme = \(theme)")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    private static func formatNumber(_ value: Double) -> String {
        value == value.rounded() ? String(Int(value)) : String(value)
    }
}

public enum TerminalError: Error, Sendable, Equatable {
    case libraryInitFailed(Int32)
    case configurationFailed([String])
    case appCreationFailed
    case surfaceCreationFailed
}

enum Log {
    static let terminal = Logger(subsystem: "tech.wolff.Constellation", category: "terminal")
}
